version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres-python
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./res:/res
